version: '3.8'

services:
  db:
    container_name: db
    image: postgres:15.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5450:5432"
  proxy:
    container_name: proxy-container
    build: .
    depends_on:
      db:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: [ "./proxy" ]
